### ISSUE TITLE
Allow custom keys in `send()` method

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/ccat-api-ts#11]
The `send` method expects `text` and `prompt_settings` keys, but only three keys are allowed in prompt settings (i.e. `use_declarative_memory`, `use_episodic_memory` and `use_procedural_memory`.

It could be useful to allow custom keys to be sent via WebSocket to share custom data in plugins.

**Comment by zAlweNy26** [comment]
You are right, I will fix it as soon as possible.
